from enum import Enum

#  region default enums
class ACLType(Enum):
    ACL_NONE = 0
    ACL_WHITE_LIST = 1
    ACL_BLACK_LIST = 2


class AwayStatus(Enum):
    AWAY_NONE = 0
    AWAY_ZZZ = 1


class BBCodeTags(Enum):
    BBCodeTag_B = 0x00000001
    BBCodeTag_I = 0x00000002
    BBCodeTag_U = 0x00000004
    BBCodeTag_S = 0x00000008
    BBCodeTag_SUP = 0x00000010
    BBCodeTag_SUB = 0x00000020
    BBCodeTag_COLOR = 0x00000040
    BBCodeTag_SIZE = 0x00000080
    BBCodeTag_group_text = 0x000000FF
    BBCodeTag_LEFT = 0x00001000
    BBCodeTag_RIGHT = 0x00002000
    BBCodeTag_CENTER = 0x00004000
    BBCodeTag_group_align = 0x00007000
    BBCodeTag_URL = 0x00010000
    BBCodeTag_IMAGE = 0x00020000
    BBCodeTag_HR = 0x00040000
    BBCodeTag_LIST = 0x00100000
    BBCodeTag_LISTITEM = 0x00200000
    BBCodeTag_group_list = 0x00300000
    BBCodeTag_TABLE = 0x00400000
    BBCodeTag_TR = 0x00800000
    BBCodeTag_TH = 0x01000000
    BBCodeTag_TD = 0x02000000
    BBCodeTag_group_table = 0x03C00000
    BBCodeTag_def_simple = ((((((BBCodeTag_B | BBCodeTag_I) | BBCodeTag_U) | BBCodeTag_S) | BBCodeTag_SUP) | BBCodeTag_SUB) | BBCodeTag_COLOR) | BBCodeTag_URL
    BBCodeTag_def_simple_Img = BBCodeTag_def_simple | BBCodeTag_IMAGE
    BBCodeTag_def_extended = (((((BBCodeTag_group_text | BBCodeTag_group_align) | BBCodeTag_URL) | BBCodeTag_IMAGE) | BBCodeTag_HR) | BBCodeTag_group_list) | BBCodeTag_group_table


class ChannelProperties(Enum):
    CHANNEL_NAME = 0
    CHANNEL_TOPIC = 1
    CHANNEL_DESCRIPTION = 2
    CHANNEL_PASSWORD = 3
    CHANNEL_CODEC = 4
    CHANNEL_CODEC_QUALITY = 5
    CHANNEL_MAXCLIENTS = 6
    CHANNEL_MAXFAMILYCLIENTS = 7
    CHANNEL_ORDER = 8
    CHANNEL_FLAG_PERMANENT = 9
    CHANNEL_FLAG_SEMI_PERMANENT = 10
    CHANNEL_FLAG_DEFAULT = 11
    CHANNEL_FLAG_PASSWORD = 12
    CHANNEL_CODEC_LATENCY_FACTOR = 13
    CHANNEL_CODEC_IS_UNENCRYPTED = 14
    CHANNEL_SECURITY_SALT = 15
    CHANNEL_DELETE_DELAY = 16
    CHANNEL_ENDMARKER = 17


class ChannelPropertiesRare(Enum):
    CHANNEL_DUMMY_2 = 17
    CHANNEL_DUMMY_3 = 18
    CHANNEL_DUMMY_4 = 19
    CHANNEL_DUMMY_5 = 20
    CHANNEL_DUMMY_6 = 21
    CHANNEL_DUMMY_7 = 22
    CHANNEL_FLAG_MAXCLIENTS_UNLIMITED = 23
    CHANNEL_FLAG_MAXFAMILYCLIENTS_UNLIMITED = 24
    CHANNEL_FLAG_MAXFAMILYCLIENTS_INHERITED = 25
    CHANNEL_FLAG_ARE_SUBSCRIBED = 26
    CHANNEL_FILEPATH = 27
    CHANNEL_NEEDED_TALK_POWER = 28
    CHANNEL_FORCED_SILENCE = 29
    CHANNEL_NAME_PHONETIC = 30
    CHANNEL_ICON_ID = 31
    CHANNEL_FLAG_PRIVATE = 32
    CHANNEL_ENDMARKER_RARE = 33


class ClientCommand(Enum):
    CLIENT_COMMAND_requestConnectionInfo = 0
    CLIENT_COMMAND_requestClientMove = 1
    CLIENT_COMMAND_requestXXMuteClients = 2
    CLIENT_COMMAND_requestClientKickFromXXX = 3
    CLIENT_COMMAND_flushChannelCreation = 4
    CLIENT_COMMAND_flushChannelUpdates = 5
    CLIENT_COMMAND_requestChannelMove = 6
    CLIENT_COMMAND_requestChannelDelete = 7
    CLIENT_COMMAND_requestChannelDescription = 8
    CLIENT_COMMAND_requestChannelXXSubscribeXXX = 9
    CLIENT_COMMAND_requestServerConnectionInfo = 10
    CLIENT_COMMAND_requestSendXXXTextMsg = 11
    CLIENT_COMMAND_filetransfers = 12
    CLIENT_COMMAND_ENDMARKER = 13


class ClientProperties(Enum):
    CLIENT_UNIQUE_IDENTIFIER = 0
    CLIENT_NICKNAME = 1
    CLIENT_VERSION = 2
    CLIENT_PLATFORM = 3
    CLIENT_FLAG_TALKING = 4
    CLIENT_INPUT_MUTED = 5
    CLIENT_OUTPUT_MUTED = 6
    CLIENT_OUTPUTONLY_MUTED = 7
    CLIENT_INPUT_HARDWARE = 8
    CLIENT_OUTPUT_HARDWARE = 9
    CLIENT_INPUT_DEACTIVATED = 10
    CLIENT_IDLE_TIME = 11
    CLIENT_DEFAULT_CHANNEL = 12
    CLIENT_DEFAULT_CHANNEL_PASSWORD = 13
    CLIENT_SERVER_PASSWORD = 14
    CLIENT_META_DATA = 15
    CLIENT_IS_MUTED = 16
    CLIENT_IS_RECORDING = 17
    CLIENT_VOLUME_MODIFICATOR = 18
    CLIENT_VERSION_SIGN = 19
    CLIENT_SECURITY_HASH = 20
    CLIENT_ENDMARKER = 21


class ClientPropertiesRare(Enum):
    CLIENT_DUMMY_3 = 21
    CLIENT_DUMMY_4 = 22
    CLIENT_DUMMY_5 = 23
    CLIENT_DUMMY_6 = 24
    CLIENT_DUMMY_7 = 25
    CLIENT_DUMMY_8 = 26
    CLIENT_DUMMY_9 = 27
    CLIENT_KEY_OFFSET = 28
    CLIENT_LAST_VAR_REQUEST = 29
    CLIENT_LOGIN_NAME = 30
    CLIENT_LOGIN_PASSWORD = 31
    CLIENT_DATABASE_ID = 32
    CLIENT_CHANNEL_GROUP_ID = 33
    CLIENT_SERVERGROUPS = 34
    CLIENT_CREATED = 35
    CLIENT_LASTCONNECTED = 36
    CLIENT_TOTALCONNECTIONS = 37
    CLIENT_AWAY = 38
    CLIENT_AWAY_MESSAGE = 39
    CLIENT_TYPE = 40
    CLIENT_FLAG_AVATAR = 41
    CLIENT_TALK_POWER = 42
    CLIENT_TALK_REQUEST = 43
    CLIENT_TALK_REQUEST_MSG = 44
    CLIENT_DESCRIPTION = 45
    CLIENT_IS_TALKER = 46
    CLIENT_MONTH_BYTES_UPLOADED = 47
    CLIENT_MONTH_BYTES_DOWNLOADED = 48
    CLIENT_TOTAL_BYTES_UPLOADED = 49
    CLIENT_TOTAL_BYTES_DOWNLOADED = 50
    CLIENT_IS_PRIORITY_SPEAKER = 51
    CLIENT_UNREAD_MESSAGES = 52
    CLIENT_NICKNAME_PHONETIC = 53
    CLIENT_NEEDED_SERVERQUERY_VIEW_POWER = 54
    CLIENT_DEFAULT_TOKEN = 55
    CLIENT_ICON_ID = 56
    CLIENT_IS_CHANNEL_COMMANDER = 57
    CLIENT_COUNTRY = 58
    CLIENT_CHANNEL_GROUP_INHERITED_CHANNEL_ID = 59
    CLIENT_BADGES = 60
    CLIENT_ENDMARKER_RARE = 61


class ClientType(Enum):
    ClientType_NORMAL = 0
    ClientType_SERVERQUERY = 1


class CodecEncryptionMode(Enum):
    CODEC_ENCRYPTION_PER_CHANNEL = 0
    CODEC_ENCRYPTION_FORCED_OFF = 1
    CODEC_ENCRYPTION_FORCED_ON = 2


class CodecType(Enum):
    CODEC_SPEEX_NARROWBAND = 0
    CODEC_SPEEX_WIDEBAND = 1
    CODEC_SPEEX_ULTRAWIDEBAND = 2
    CODEC_CELT_MONO = 3
    CODEC_OPUS_VOICE = 4
    CODEC_OPUS_MUSIC = 5


class CommandLinePropertiesRare(Enum):
    COMMANDLINE_NOTHING = 0
    COMMANDLINE_ENDMARKER_RARE = 1


class ConnectionProperties(Enum):
    CONNECTION_PING = 0
    CONNECTION_PING_DEVIATION = 1
    CONNECTION_CONNECTED_TIME = 2
    CONNECTION_IDLE_TIME = 3
    CONNECTION_CLIENT_IP = 4
    CONNECTION_CLIENT_PORT = 5
    CONNECTION_SERVER_IP = 6
    CONNECTION_SERVER_PORT = 7
    CONNECTION_PACKETS_SENT_SPEECH = 8
    CONNECTION_PACKETS_SENT_KEEPALIVE = 9
    CONNECTION_PACKETS_SENT_CONTROL = 10
    CONNECTION_PACKETS_SENT_TOTAL = 11
    CONNECTION_BYTES_SENT_SPEECH = 12
    CONNECTION_BYTES_SENT_KEEPALIVE = 13
    CONNECTION_BYTES_SENT_CONTROL = 14
    CONNECTION_BYTES_SENT_TOTAL = 15
    CONNECTION_PACKETS_RECEIVED_SPEECH = 16
    CONNECTION_PACKETS_RECEIVED_KEEPALIVE = 17
    CONNECTION_PACKETS_RECEIVED_CONTROL = 18
    CONNECTION_PACKETS_RECEIVED_TOTAL = 19
    CONNECTION_BYTES_RECEIVED_SPEECH = 20
    CONNECTION_BYTES_RECEIVED_KEEPALIVE = 21
    CONNECTION_BYTES_RECEIVED_CONTROL = 22
    CONNECTION_BYTES_RECEIVED_TOTAL = 23
    CONNECTION_PACKETLOSS_SPEECH = 24
    CONNECTION_PACKETLOSS_KEEPALIVE = 25
    CONNECTION_PACKETLOSS_CONTROL = 26
    CONNECTION_PACKETLOSS_TOTAL = 27
    CONNECTION_SERVER2CLIENT_PACKETLOSS_SPEECH = 28
    CONNECTION_SERVER2CLIENT_PACKETLOSS_KEEPALIVE = 29
    CONNECTION_SERVER2CLIENT_PACKETLOSS_CONTROL = 30
    CONNECTION_SERVER2CLIENT_PACKETLOSS_TOTAL = 31
    CONNECTION_CLIENT2SERVER_PACKETLOSS_SPEECH = 32
    CONNECTION_CLIENT2SERVER_PACKETLOSS_KEEPALIVE = 33
    CONNECTION_CLIENT2SERVER_PACKETLOSS_CONTROL = 34
    CONNECTION_CLIENT2SERVER_PACKETLOSS_TOTAL = 35
    CONNECTION_BANDWIDTH_SENT_LAST_SECOND_SPEECH = 36
    CONNECTION_BANDWIDTH_SENT_LAST_SECOND_KEEPALIVE = 37
    CONNECTION_BANDWIDTH_SENT_LAST_SECOND_CONTROL = 38
    CONNECTION_BANDWIDTH_SENT_LAST_SECOND_TOTAL = 39
    CONNECTION_BANDWIDTH_SENT_LAST_MINUTE_SPEECH = 40
    CONNECTION_BANDWIDTH_SENT_LAST_MINUTE_KEEPALIVE = 41
    CONNECTION_BANDWIDTH_SENT_LAST_MINUTE_CONTROL = 42
    CONNECTION_BANDWIDTH_SENT_LAST_MINUTE_TOTAL = 43
    CONNECTION_BANDWIDTH_RECEIVED_LAST_SECOND_SPEECH = 44
    CONNECTION_BANDWIDTH_RECEIVED_LAST_SECOND_KEEPALIVE = 45
    CONNECTION_BANDWIDTH_RECEIVED_LAST_SECOND_CONTROL = 46
    CONNECTION_BANDWIDTH_RECEIVED_LAST_SECOND_TOTAL = 47
    CONNECTION_BANDWIDTH_RECEIVED_LAST_MINUTE_SPEECH = 48
    CONNECTION_BANDWIDTH_RECEIVED_LAST_MINUTE_KEEPALIVE = 49
    CONNECTION_BANDWIDTH_RECEIVED_LAST_MINUTE_CONTROL = 50
    CONNECTION_BANDWIDTH_RECEIVED_LAST_MINUTE_TOTAL = 51
    CONNECTION_ENDMARKER = 52


class ConnectionPropertiesRare(Enum):
    CONNECTION_DUMMY_0 = 52
    CONNECTION_DUMMY_1 = 53
    CONNECTION_DUMMY_2 = 54
    CONNECTION_DUMMY_3 = 55
    CONNECTION_DUMMY_4 = 56
    CONNECTION_DUMMY_5 = 57
    CONNECTION_DUMMY_6 = 58
    CONNECTION_DUMMY_7 = 59
    CONNECTION_DUMMY_8 = 60
    CONNECTION_DUMMY_9 = 61
    CONNECTION_FILETRANSFER_BANDWIDTH_SENT = 62
    CONNECTION_FILETRANSFER_BANDWIDTH_RECEIVED = 63
    CONNECTION_FILETRANSFER_BYTES_RECEIVED_TOTAL = 64
    CONNECTION_FILETRANSFER_BYTES_SENT_TOTAL = 65
    CONNECTION_ENDMARKER_RARE = 66


class ConnectStatus(Enum):
    STATUS_DISCONNECTED = 0
    STATUS_CONNECTING = 1
    STATUS_CONNECTED = 2
    STATUS_CONNECTION_ESTABLISHING = 3
    STATUS_CONNECTION_ESTABLISHED = 4


class FileListType(Enum):
    FileListType_Directory = 0
    FileListType_File = 1


class FileTransferState(Enum):
    FILETRANSFER_INITIALISING = 0
    FILETRANSFER_ACTIVE = 1
    FILETRANSFER_FINISHED = 2


class FTAction(Enum):
    FT_INIT_SERVER = 0
    FT_INIT_CHANNEL = 1
    FT_UPLOAD = 2
    FT_DOWNLOAD = 3
    FT_DELETE = 4
    FT_CREATEDIR = 5
    FT_RENAME = 6
    FT_FILELIST = 7
    FT_FILEINFO = 8


class GroupShowNameTreeMode(Enum):
    GroupShowNameTreeMode_NONE = 0
    GroupShowNameTreeMode_BEFORE = 1
    GroupShowNameTreeMode_BEHIND = 2


class GroupWhisperTargetMode(Enum):
    GROUPWHISPERTARGETMODE_ALL = 0
    GROUPWHISPERTARGETMODE_CURRENTCHANNEL = 1
    GROUPWHISPERTARGETMODE_PARENTCHANNEL = 2
    GROUPWHISPERTARGETMODE_ALLPARENTCHANNELS = 3
    GROUPWHISPERTARGETMODE_CHANNELFAMILY = 4
    GROUPWHISPERTARGETMODE_ANCESTORCHANNELFAMILY = 5
    GROUPWHISPERTARGETMODE_SUBCHANNELS = 6
    GROUPWHISPERTARGETMODE_ENDMARKER = 7


class GroupWhisperType(Enum):
    GROUPWHISPERTYPE_SERVERGROUP = 0
    GROUPWHISPERTYPE_CHANNELGROUP = 1
    GROUPWHISPERTYPE_CHANNELCOMMANDER = 2
    GROUPWHISPERTYPE_ALLCLIENTS = 3
    GROUPWHISPERTYPE_ENDMARKER = 4


class HardwareInputStatus(Enum):
    HARDWAREINPUT_DISABLED = 0
    HARDWAREINPUT_ENABLED = 1


class HardwareOutputStatus(Enum):
    HARDWAREOUTPUT_DISABLED = 0
    HARDWAREOUTPUT_ENABLED = 1


class HostBannerMode(Enum):
    HostBannerMode_NO_ADJUST = 0
    HostBannerMode_ADJUST_IGNORE_ASPECT = 1
    HostBannerMode_ADJUST_KEEP_ASPECT = 2


class HostMessageMode(Enum):
    HostMessageMode_NONE = 0
    HostMessageMode_LOG = 1
    HostMessageMode_MODAL = 2
    HostMessageMode_MODALQUIT = 3


class InputDeactivationStatus(Enum):
    INPUT_ACTIVE = 0
    INPUT_DEACTIVATED = 1


class LicenseViolationType(Enum):
    NO_VIOLATION = 0
    SLOT_VIOLATION = 1
    SLOT_SUSPICION = 2


class LocalTestMode(Enum):
    TEST_MODE_OFF = 0
    TEST_MODE_VOICE_LOCAL_ONLY = 1
    TEST_MODE_VOICE_LOCAL_AND_REMOTE = 2


class LogLevel(Enum):
    LogLevel_CRITICAL = 0
    LogLevel_ERROR = 1
    LogLevel_WARNING = 2
    LogLevel_DEBUG = 3
    LogLevel_INFO = 4
    LogLevel_DEVEL = 5


class LogTypes(Enum):
    LogType_NONE = 0x0000
    LogType_FILE = 0x0001
    LogType_CONSOLE = 0x0002
    LogType_USERLOGGING = 0x0004
    LogType_NO_NETLOGGING = 0x0008
    LogType_DATABASE = 0x0010
    LogType_SYSLOG = 0x0020


class MonoSoundDestination(Enum):
    MONO_SOUND_DESTINATION_ALL = 0
    MONO_SOUND_DESTINATION_FRONT_CENTER = 1
    MONO_SOUND_DESTINATION_FRONT_LEFT_AND_RIGHT = 2


class MuteInputStatus(Enum):
    MUTEINPUT_NONE = 0
    MUTEINPUT_MUTED = 1


class MuteOutputStatus(Enum):
    MUTEOUTPUT_NONE = 0
    MUTEOUTPUT_MUTED = 1


class PluginConfigureOffer(Enum):
    PLUGIN_OFFERS_NO_CONFIGURE = 0
    PLUGIN_OFFERS_CONFIGURE_NEW_THREAD = 1
    PLUGIN_OFFERS_CONFIGURE_QT_THREAD = 2


class PluginConnectTab(Enum):
    PLUGIN_CONNECT_TAB_NEW = 0
    PLUGIN_CONNECT_TAB_CURRENT = 1
    PLUGIN_CONNECT_TAB_NEW_IF_CURRENT_CONNECTED = 2


class PluginGuiProfile(Enum):
    PLUGIN_GUI_SOUND_CAPTURE = 0
    PLUGIN_GUI_SOUND_PLAYBACK = 1
    PLUGIN_GUI_HOTKEY = 2
    PLUGIN_GUI_SOUNDPACK = 3
    PLUGIN_GUI_IDENTITY = 4


class PluginItemType(Enum):
    PLUGIN_SERVER = 0
    PLUGIN_CHANNEL = 1
    PLUGIN_CLIENT = 2


class PluginMenuType(Enum):
    PLUGIN_MENU_TYPE_GLOBAL = 0
    PLUGIN_MENU_TYPE_CHANNEL = 1
    PLUGIN_MENU_TYPE_CLIENT = 2


class PluginMessageTarget(Enum):
    PLUGIN_MESSAGE_TARGET_SERVER = 0
    PLUGIN_MESSAGE_TARGET_CHANNEL = 1


class PluginTargetMode(Enum):
    PluginCommandTarget_CURRENT_CHANNEL = 0
    PluginCommandTarget_SERVER = 1
    PluginCommandTarget_CLIENT = 2
    PluginCommandTarget_CURRENT_CHANNEL_SUBSCRIBED_CLIENTS = 3
    PluginCommandTarget_MAX = 4


class ReasonIdentifier(Enum):
    REASON_NONE = 0
    REASON_MOVED = 1
    REASON_SUBSCRIPTION = 2
    REASON_LOST_CONNECTION = 3
    REASON_KICK_CHANNEL = 4
    REASON_KICK_SERVER = 5
    REASON_KICK_SERVER_BAN = 6
    REASON_SERVERSTOP = 7
    REASON_CLIENTDISCONNECT = 8
    REASON_CHANNELUPDATE = 9
    REASON_CHANNELEDIT = 10
    REASON_CLIENTDISCONNECT_SERVER_SHUTDOWN = 11


class SecuritySaltOptions(Enum):
    SECURITY_SALT_CHECK_NICKNAME = 1
    SECURITY_SALT_CHECK_META_DATA = 2


class SERVER_BINDING(Enum):
    SERVER_BINDING_VIRTUALSERVER = 0
    SERVER_BINDING_SERVERQUERY = 1
    SERVER_BINDING_FILETRANSFER = 2


class ServerInstancePropertiesRare(Enum):
    SERVERINSTANCE_DATABASE_VERSION = 0
    SERVERINSTANCE_FILETRANSFER_PORT = 1
    SERVERINSTANCE_SERVER_ENTROPY = 2
    SERVERINSTANCE_MONTHLY_TIMESTAMP = 3
    SERVERINSTANCE_MAX_DOWNLOAD_TOTAL_BANDWIDTH = 4
    SERVERINSTANCE_MAX_UPLOAD_TOTAL_BANDWIDTH = 5
    SERVERINSTANCE_GUEST_SERVERQUERY_GROUP = 6
    SERVERINSTANCE_SERVERQUERY_FLOOD_COMMANDS = 7
    SERVERINSTANCE_SERVERQUERY_FLOOD_TIME = 8
    SERVERINSTANCE_SERVERQUERY_BAN_TIME = 9
    SERVERINSTANCE_TEMPLATE_SERVERADMIN_GROUP = 10
    SERVERINSTANCE_TEMPLATE_SERVERDEFAULT_GROUP = 11
    SERVERINSTANCE_TEMPLATE_CHANNELADMIN_GROUP = 12
    SERVERINSTANCE_TEMPLATE_CHANNELDEFAULT_GROUP = 13
    SERVERINSTANCE_PERMISSIONS_VERSION = 14
    SERVERINSTANCE_PENDING_CONNECTIONS_PER_IP = 15
    SERVERINSTANCE_ENDMARKER_RARE = 16


class TalkStatus(Enum):
    STATUS_NOT_TALKING = 0
    STATUS_TALKING = 1
    STATUS_TALKING_WHILE_DISABLED = 2


class TextMessageTargetMode(Enum):
    TextMessageTarget_CLIENT = 1
    TextMessageTarget_CHANNEL = 2
    TextMessageTarget_SERVER = 3
    TextMessageTarget_MAX = 4


class VirtualServerProperties(Enum):
    VIRTUALSERVER_UNIQUE_IDENTIFIER = 0
    VIRTUALSERVER_NAME = 1
    VIRTUALSERVER_WELCOMEMESSAGE = 2
    VIRTUALSERVER_PLATFORM = 3
    VIRTUALSERVER_VERSION = 4
    VIRTUALSERVER_MAXCLIENTS = 5
    VIRTUALSERVER_PASSWORD = 6
    VIRTUALSERVER_CLIENTS_ONLINE = 7
    VIRTUALSERVER_CHANNELS_ONLINE = 8
    VIRTUALSERVER_CREATED = 9
    VIRTUALSERVER_UPTIME = 10
    VIRTUALSERVER_CODEC_ENCRYPTION_MODE = 11
    VIRTUALSERVER_ENDMARKER = 12


class VirtualServerPropertiesRare(Enum):
    VIRTUALSERVER_DUMMY_0 = 12
    VIRTUALSERVER_DUMMY_1 = 13
    VIRTUALSERVER_DUMMY_2 = 14
    VIRTUALSERVER_DUMMY_3 = 15
    VIRTUALSERVER_DUMMY_4 = 16
    VIRTUALSERVER_DUMMY_5 = 17
    VIRTUALSERVER_DUMMY_6 = 18
    VIRTUALSERVER_DUMMY_7 = 19
    VIRTUALSERVER_DUMMY_8 = 20
    VIRTUALSERVER_KEYPAIR = 21
    VIRTUALSERVER_HOSTMESSAGE = 22
    VIRTUALSERVER_HOSTMESSAGE_MODE = 23
    VIRTUALSERVER_FILEBASE = 24
    VIRTUALSERVER_DEFAULT_SERVER_GROUP = 25
    VIRTUALSERVER_DEFAULT_CHANNEL_GROUP = 26
    VIRTUALSERVER_FLAG_PASSWORD = 27
    VIRTUALSERVER_DEFAULT_CHANNEL_ADMIN_GROUP = 28
    VIRTUALSERVER_MAX_DOWNLOAD_TOTAL_BANDWIDTH = 29
    VIRTUALSERVER_MAX_UPLOAD_TOTAL_BANDWIDTH = 30
    VIRTUALSERVER_HOSTBANNER_URL = 31
    VIRTUALSERVER_HOSTBANNER_GFX_URL = 32
    VIRTUALSERVER_HOSTBANNER_GFX_INTERVAL = 33
    VIRTUALSERVER_COMPLAIN_AUTOBAN_COUNT = 34
    VIRTUALSERVER_COMPLAIN_AUTOBAN_TIME = 35
    VIRTUALSERVER_COMPLAIN_REMOVE_TIME = 36
    VIRTUALSERVER_MIN_CLIENTS_IN_CHANNEL_BEFORE_FORCED_SILENCE = 37
    VIRTUALSERVER_PRIORITY_SPEAKER_DIMM_MODIFICATOR = 38
    VIRTUALSERVER_ID = 39
    VIRTUALSERVER_ANTIFLOOD_POINTS_TICK_REDUCE = 40
    VIRTUALSERVER_ANTIFLOOD_POINTS_NEEDED_COMMAND_BLOCK = 41
    VIRTUALSERVER_ANTIFLOOD_POINTS_NEEDED_IP_BLOCK = 42
    VIRTUALSERVER_CLIENT_CONNECTIONS = 43
    VIRTUALSERVER_QUERY_CLIENT_CONNECTIONS = 44
    VIRTUALSERVER_HOSTBUTTON_TOOLTIP = 45
    VIRTUALSERVER_HOSTBUTTON_URL = 46
    VIRTUALSERVER_HOSTBUTTON_GFX_URL = 47
    VIRTUALSERVER_QUERYCLIENTS_ONLINE = 48
    VIRTUALSERVER_DOWNLOAD_QUOTA = 49
    VIRTUALSERVER_UPLOAD_QUOTA = 50
    VIRTUALSERVER_MONTH_BYTES_DOWNLOADED = 51
    VIRTUALSERVER_MONTH_BYTES_UPLOADED = 52
    VIRTUALSERVER_TOTAL_BYTES_DOWNLOADED = 53
    VIRTUALSERVER_TOTAL_BYTES_UPLOADED = 54
    VIRTUALSERVER_PORT = 55
    VIRTUALSERVER_AUTOSTART = 56
    VIRTUALSERVER_MACHINE_ID = 57
    VIRTUALSERVER_NEEDED_IDENTITY_SECURITY_LEVEL = 58
    VIRTUALSERVER_LOG_CLIENT = 59
    VIRTUALSERVER_LOG_QUERY = 60
    VIRTUALSERVER_LOG_CHANNEL = 61
    VIRTUALSERVER_LOG_PERMISSIONS = 62
    VIRTUALSERVER_LOG_SERVER = 63
    VIRTUALSERVER_LOG_FILETRANSFER = 64
    VIRTUALSERVER_MIN_CLIENT_VERSION = 65
    VIRTUALSERVER_NAME_PHONETIC = 66
    VIRTUALSERVER_ICON_ID = 67
    VIRTUALSERVER_RESERVED_SLOTS = 68
    VIRTUALSERVER_TOTAL_PACKETLOSS_SPEECH = 69
    VIRTUALSERVER_TOTAL_PACKETLOSS_KEEPALIVE = 70
    VIRTUALSERVER_TOTAL_PACKETLOSS_CONTROL = 71
    VIRTUALSERVER_TOTAL_PACKETLOSS_TOTAL = 72
    VIRTUALSERVER_TOTAL_PING = 73
    VIRTUALSERVER_IP = 74
    VIRTUALSERVER_WEBLIST_ENABLED = 75
    VIRTUALSERVER_AUTOGENERATED_PRIVILEGEKEY = 76
    VIRTUALSERVER_ASK_FOR_PRIVILEGEKEY = 77
    VIRTUALSERVER_HOSTBANNER_MODE = 78
    VIRTUALSERVER_CHANNEL_TEMP_DELETE_DELAY_DEFAULT = 79
    VIRTUALSERVER_MIN_ANDROID_VERSION = 80
    VIRTUALSERVER_MIN_IOS_VERSION = 81
    VIRTUALSERVER_MIN_WINPHONE_VERSION = 82
    VIRTUALSERVER_ENDMARKER_RARE = 83

class Visibility(Enum):
    ENTER_VISIBILITY = 0
    RETAIN_VISIBILITY = 1
    LEAVE_VISIBILITY = 2
#endregion
#region custom enums
class AddonStatus(Enum):
    UNKNOWN = 0
    INSTALLED = 1
    LOADED = 2
    ENABLED = 3

class ContactStatus(object):
    """
    Order is important!
    """
    FRIEND = 0
    BLOCKED = 1
    NEUTRAL = 2
    UNKNOWN = 3

class ExtendedAddonStatus(Enum):
    UNKNOWN = 0
    FOLDER = 1
    DATABASE = 2
    MEMORY = 3

class ServerInstanceType(Enum):
    UNKNOWN = 0
    VANILLA = 1
    SDK = 2
    TEASPEAK = 3

class ServerTreeItemType(Enum):
    UNKNOWN = 0
    SERVER = 1
    CHANNEL = 2
    CLIENT = 3

class GroupType(Enum):
    TEMPLATE = 0
    REGULAR = 1
    QUERY = 2
    UNKNOWN = 3

class AntiFloodPoints(Enum):
    AUTH = 0
    BANADD = 25
    BANCLIENT = 25
    BANDEL = 5
    BANDELALL = 5
    BANLIST = 25
    BINDINGLIST = 0
    CHANNELADDPERM = 5
    CHANNELCLIENTADDPERM = 5
    CHANNELCLIENTDELPERM = 5
    CHANNELCLIENTLIST = 0
    CHANNELCLIENTPERMLIST = 5
    CHANNELCONNECTINFO = 0
    CHANNELCREATE = 25
    CHANNELCREATEPRIVATE = 25
    CHANNELDELETE = 25
    CHANNELDELPERM = 5
    CHANNELEDIT = 25
    CHANNELFIND = 0
    CHANNELGETDESCRIPTION = 0
    CHANNELGROUPADD = 5
    CHANNELGROUPADDPERM = 5
    CHANNELGROUPCLIENTLIST = 5
    CHANNELGROUPCOPY = 5
    CHANNELGROUPDEL = 5
    CHANNELGROUPDELPERM = 5
    CHANNELGROUPLIST = 5
    CHANNELGROUPPERMLIST = 5
    CHANNELGROUPRENAME = 5
    CHANNELINFO = 0
    CHANNELLIST = 0
    CHANNELMOVE = 25
    CHANNELPERMLIST = 5
    CHANNELSUBSCRIBE = 15
    CHANNELSUBSCRIBEALL = 20
    CHANNELUNSUBSCRIBE = 5
    CHANNELUNSUBSCRIBEALL = 25
    CHANNELVARIABLE = 0
    CLIENTADDPERM = 5
    CLIENTCHATCLOSED = 5
    CLIENTCHATCOMPOSING = 0
    CLIENTDBDELETE = 25
    CLIENTDBEDIT = 25
    CLIENTDBFIND = 50
    CLIENTDBINFO = 0
    CLIENTDBLIST = 25
    CLIENTDELPERM = 5
    CLIENTDISCONNECT = 0
    CLIENTEDIT = 25
    CLIENTFIND = 0
    CLIENTGETDBIDFROMUID = 5
    CLIENTGETIDS = 5
    CLIENTGETNAMEFROMDBID = 5
    CLIENTGETNAMEFROMUID = 5
    CLIENTGETUIDFROMCLID = 5
    CLIENTGETVARIABLES = 0
    CLIENTINFO = 0
    CLIENTINIT = 0
    CLIENTINITIV = 0
    CLIENTKICK = 25
    CLIENTLIST = 0
    CLIENTMOVE = 10
    CLIENTMUTE = 10
    CLIENTNOTIFYREGISTER = 0
    CLIENTNOTIFYUNREGISTER = 0
    CLIENTPERMLIST = 5
    CLIENTPOKE = 25
    CLIENTSETSERVERQUERYLOGIN = 25
    CLIENTSITEREPORT = 0
    CLIENTUNMUTE = 10
    CLIENTUPDATE = 15
    CLIENTVARIABLE = 0
    COMPLAINADD = 25
    COMPLAINDEL = 5
    COMPLAINDELALL = 25
    COMPLAINLIST = 25
    CONNECTIONINFOAUTOUPDATE = 0
    CURRENTSCHANDLERID = 0
    CUSTOMINFO = 0
    CUSTOMSEARCH = 50
    DUMMY_CONNECTFAILED = 0
    DUMMY_CONNECTIONLOST = 0
    DUMMY_NEWIP = 0
    FTCREATEDIR = 5
    FTDELETEFILE = 5
    FTGETFILEINFO = 5
    FTGETFILELIST = 0
    FTINITDOWNLOAD = 0
    FTINITUPLOAD = 0
    FTLIST = 5
    FTRENAMEFILE = 5
    FTSTOP = 5
    GETCONNECTIONINFO = 0
    GM = 50
    HASHPASSWORD = 0
    HELP = 0
    INSTANCEEDIT = 25
    INSTANCEINFO = 0
    LOGADD = 0
    LOGIN = 0
    LOGOUT = 0
    LOGVIEW = 50
    MESSAGEADD = 25
    MESSAGEDEL = 5
    MESSAGEGET = 20
    MESSAGELIST = 25
    MESSAGEUPDATEFLAG = 5
    PERMFIND = 0
    PERMGET = 0
    PERMIDGETBYNAME = 0
    PERMISSIONLIST = 5
    PERMOVERVIEW = 5
    PERMRESET = 0
    PLUGINCMD = 5
    PRIVILEGEKEYADD = 0
    PRIVILEGEKEYDELETE = 0
    PRIVILEGEKEYLIST = 0
    PRIVILEGEKEYUSE = 0
    QUIT = 0
    SERVERCONNECTINFO = 0
    SERVERCONNECTIONHANDLERLIST = 0
    SERVERCREATE = 0
    SERVERDELETE = 0
    SERVEREDIT = 5
    SERVERGETVARIABLES = 0
    SERVERGROUPADD = 5
    SERVERGROUPADDCLIENT = 25
    SERVERGROUPADDPERM = 5
    SERVERGROUPAUTOADDPERM = 0
    SERVERGROUPAUTODELPERM = 0
    SERVERGROUPCLIENTLIST = 5
    SERVERGROUPCOPY = 5
    SERVERGROUPDEL = 5
    SERVERGROUPDELCLIENT = 25
    SERVERGROUPDELPERM = 5
    SERVERGROUPLIST = 5
    SERVERGROUPPERMLIST = 5
    SERVERGROUPRENAME = 5
    SERVERGROUPSBYCLIENTID = 5
    SERVERIDGETBYPORT = 0
    SERVERINFO = 0
    SERVERLIST = 0
    SERVERNOTIFYREGISTER = 0
    SERVERNOTIFYUNREGISTER = 0
    SERVERPROCESSSTOP = 0
    SERVERQUERYCMD = 5
    SERVERREQUESTCONNECTIONINFO  = 0
    SERVERSNAPSHOTCREATE = 0
    SERVERSNAPSHOTDEPLOY = 0
    SERVERSTART = 0
    SERVERSTOP = 0
    SERVERTEMPPASSWORDADD = 5
    SERVERTEMPPASSWORDDEL = 5
    SERVERTEMPPASSWORDLIST = 5
    SERVERVARIABLE = 0
    SETCLIENTCHANNELGROUP = 25
    SETCONNECTIONINFO = 0
    SETWHISPERLIST = 0
    TEXTMESSAGESEND = 15
    TOKENADD = 5
    TOKENDELETE = 5
    TOKENLIST = 5
    TOKENUSE = 5
    USE = 0
    VERIFYCHANNELPASSWORD = 5
    VERIFYSERVERPASSWORD = 5
    VERSION = 0
    WHOAMI = 0

class color(Enum):
    DEFAULT = "[color=white]"
    DEBUG = "[color=grey]"
    INFO = "[color=lightblue]"
    SUCCESS = "[color=green]"
    WARNING = "[color=orange]"
    ERROR = "[color=red]"
    FATAL = "[color=darkred]"
    ENDMARKER = "[/color]"
#endregion